<?php

/**
 * IDaaS API
 * PHP version 8.1
 *
 * @package Mydex\ApiIdaasSdk\Slim4
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * Identity as a Service API for member authentication, identifiers, and account management.
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 * Extend this class with your controller. You can inject dependencies via class constructor,
 * @see https://github.com/PHP-DI/Slim-Bridge basic example.
 */
namespace Mydex\ApiIdaasSdk\Slim4\Api;

use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Message\ResponseInterface;
use Slim\Exception\HttpNotImplementedException;

/**
 * AbstractIdentifiersApi Class Doc Comment
 *
 * @package Mydex\ApiIdaasSdk\Slim4\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
abstract class AbstractIdentifiersApi
{
    /**
     * GET getIdentifierInvite
     * Summary: Fetch an invitation code and identifier auth data.
     * Notes: Retrieves the invitation data for a given invite code.
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param string $invite The invitation code
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function getIdentifierInvite(
        ServerRequestInterface $request,
        ResponseInterface $response,
        string $invite
    ): ResponseInterface {
        $message = "How about implementing getIdentifierInvite as a GET method in Mydex\ApiIdaasSdk\Slim4\Api\IdentifiersApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * PATCH patchNotifyStatus
     * Summary: Update the status of a notification.
     * Notes: Updates the status of a notification identifier.
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function patchNotifyStatus(
        ServerRequestInterface $request,
        ResponseInterface $response
    ): ResponseInterface {
        $body = $request->getParsedBody();
        $message = "How about implementing patchNotifyStatus as a PATCH method in Mydex\ApiIdaasSdk\Slim4\Api\IdentifiersApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * POST postInviteStatus
     * Summary: Check the status of an invite.
     * Notes: Checks the status of an invitation without modifying it.
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function postInviteStatus(
        ServerRequestInterface $request,
        ResponseInterface $response
    ): ResponseInterface {
        $body = $request->getParsedBody();
        $message = "How about implementing postInviteStatus as a POST method in Mydex\ApiIdaasSdk\Slim4\Api\IdentifiersApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * POST postNotifyMemberViaIdentifier
     * Summary: Send a notification to a member via its identifier.
     * Notes: Sends a notification (email or SMS) to a member using their identifier for authentication.
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function postNotifyMemberViaIdentifier(
        ServerRequestInterface $request,
        ResponseInterface $response
    ): ResponseInterface {
        $body = $request->getParsedBody();
        $message = "How about implementing postNotifyMemberViaIdentifier as a POST method in Mydex\ApiIdaasSdk\Slim4\Api\IdentifiersApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * POST postStoreAndSendIdentifierInvite
     * Summary: Store an invitation code and send notification.
     * Notes: Stores an invitation code and sends an invitation to the member via their identifier.
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function postStoreAndSendIdentifierInvite(
        ServerRequestInterface $request,
        ResponseInterface $response
    ): ResponseInterface {
        $body = $request->getParsedBody();
        $message = "How about implementing postStoreAndSendIdentifierInvite as a POST method in Mydex\ApiIdaasSdk\Slim4\Api\IdentifiersApi class?";
        throw new HttpNotImplementedException($request, $message);
    }
}
