<?php

/**
 * IDaaS API
 * PHP version 8.1
 *
 * @package Mydex\ApiIdaasSdk\Slim4
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * Identity as a Service API for member authentication, identifiers, and account management.
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 * Extend this class with your controller. You can inject dependencies via class constructor,
 * @see https://github.com/PHP-DI/Slim-Bridge basic example.
 */
namespace Mydex\ApiIdaasSdk\Slim4\Api;

use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Message\ResponseInterface;
use Slim\Exception\HttpNotImplementedException;

/**
 * AbstractConnectionsApi Class Doc Comment
 *
 * @package Mydex\ApiIdaasSdk\Slim4\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
abstract class AbstractConnectionsApi
{
    /**
     * POST postFtcSetup
     * Summary: Set up a First Time Connection URL.
     * Notes: Generates a one-time URL for a member to complete First Time Connection. Requires OAuth2.0 authentication.
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function postFtcSetup(
        ServerRequestInterface $request,
        ResponseInterface $response
    ): ResponseInterface {
        $body = $request->getParsedBody();
        $message = "How about implementing postFtcSetup as a POST method in Mydex\ApiIdaasSdk\Slim4\Api\ConnectionsApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * POST postIdentify
     * Summary: Set up an identification URL.
     * Notes: Generates a one-time URL for identifying a member without requiring them to know their MydexID. Requires OAuth2.0 authentication.
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function postIdentify(
        ServerRequestInterface $request,
        ResponseInterface $response
    ): ResponseInterface {
        $body = $request->getParsedBody();
        $message = "How about implementing postIdentify as a POST method in Mydex\ApiIdaasSdk\Slim4\Api\ConnectionsApi class?";
        throw new HttpNotImplementedException($request, $message);
    }
}
