<?php

/**
 * IDaaS API
 * PHP version 8.1
 *
 * @package Mydex\ApiIdaasSdk\Slim4
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * Identity as a Service API for member authentication, identifiers, and account management.
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 * Extend this class with your controller. You can inject dependencies via class constructor,
 * @see https://github.com/PHP-DI/Slim-Bridge basic example.
 */
namespace Mydex\ApiIdaasSdk\Slim4\Api;

use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Message\ResponseInterface;
use Slim\Exception\HttpNotImplementedException;

/**
 * AbstractScotAccountApi Class Doc Comment
 *
 * @package Mydex\ApiIdaasSdk\Slim4\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
abstract class AbstractScotAccountApi
{
    /**
     * GET getMydexIdFromScotAccountSub
     * Summary: Check if a ScotAccount sub GUID has an associated MydexID.
     * Notes: Retrieves the MydexID associated with a ScotAccount GUID.
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param string $sub The ScotAccount GUID
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function getMydexIdFromScotAccountSub(
        ServerRequestInterface $request,
        ResponseInterface $response,
        string $sub
    ): ResponseInterface {
        $message = "How about implementing getMydexIdFromScotAccountSub as a GET method in Mydex\ApiIdaasSdk\Slim4\Api\ScotAccountApi class?";
        throw new HttpNotImplementedException($request, $message);
    }
}
