<?php

/**
 * IDaaS API
 * PHP version 8.1
 *
 * @package Mydex\ApiIdaasSdk\Slim4
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * Identity as a Service API for member authentication, identifiers, and account management.
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the endpoint.
 */
namespace Mydex\ApiIdaasSdk\Slim4\Api;

use PHPUnit\Framework\TestCase;
use Mydex\ApiIdaasSdk\Slim4\Api\IdentifiersApi;

/**
 * IdentifiersApiTest Class Doc Comment
 *
 * @package Mydex\ApiIdaasSdk\Slim4\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \Mydex\ApiIdaasSdk\Slim4\Api\IdentifiersApi
 */
class IdentifiersApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getIdentifierInvite
     *
     * Fetch an invitation code and identifier auth data..
     *
     * @covers ::getIdentifierInvite
     */
    public function testGetIdentifierInvite()
    {
        self::markTestIncomplete(
            'Test of "getIdentifierInvite" method has not been implemented yet.'
        );
    }

    /**
     * Test case for patchNotifyStatus
     *
     * Update the status of a notification..
     *
     * @covers ::patchNotifyStatus
     */
    public function testPatchNotifyStatus()
    {
        self::markTestIncomplete(
            'Test of "patchNotifyStatus" method has not been implemented yet.'
        );
    }

    /**
     * Test case for postInviteStatus
     *
     * Check the status of an invite..
     *
     * @covers ::postInviteStatus
     */
    public function testPostInviteStatus()
    {
        self::markTestIncomplete(
            'Test of "postInviteStatus" method has not been implemented yet.'
        );
    }

    /**
     * Test case for postNotifyMemberViaIdentifier
     *
     * Send a notification to a member via its identifier..
     *
     * @covers ::postNotifyMemberViaIdentifier
     */
    public function testPostNotifyMemberViaIdentifier()
    {
        self::markTestIncomplete(
            'Test of "postNotifyMemberViaIdentifier" method has not been implemented yet.'
        );
    }

    /**
     * Test case for postStoreAndSendIdentifierInvite
     *
     * Store an invitation code and send notification..
     *
     * @covers ::postStoreAndSendIdentifierInvite
     */
    public function testPostStoreAndSendIdentifierInvite()
    {
        self::markTestIncomplete(
            'Test of "postStoreAndSendIdentifierInvite" method has not been implemented yet.'
        );
    }
}
