<?php

/**
 * IDaaS API
 * PHP version 8.1
 *
 * @package Mydex\ApiIdaasSdk\Slim4
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * Identity as a Service API for member authentication, identifiers, and account management.
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the endpoint.
 */
namespace Mydex\ApiIdaasSdk\Slim4\Api;

use PHPUnit\Framework\TestCase;
use Mydex\ApiIdaasSdk\Slim4\Api\ScotAccountApi;

/**
 * ScotAccountApiTest Class Doc Comment
 *
 * @package Mydex\ApiIdaasSdk\Slim4\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \Mydex\ApiIdaasSdk\Slim4\Api\ScotAccountApi
 */
class ScotAccountApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getMydexIdFromScotAccountSub
     *
     * Check if a ScotAccount sub GUID has an associated MydexID..
     *
     * @covers ::getMydexIdFromScotAccountSub
     */
    public function testGetMydexIdFromScotAccountSub()
    {
        self::markTestIncomplete(
            'Test of "getMydexIdFromScotAccountSub" method has not been implemented yet.'
        );
    }
}
