<?php

/**
 * IDaaS API
 * PHP version 8.1
 *
 * @package Mydex\ApiIdaasSdk\Slim4
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * Identity as a Service API for member authentication, identifiers, and account management.
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace Mydex\ApiIdaasSdk\Slim4\Model;

use Mydex\ApiIdaasSdk\Slim4\BaseModel;

/**
 * AuthErrorResponseError
 *
 * @package Mydex\ApiIdaasSdk\Slim4\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class AuthErrorResponseError extends BaseModel
{
    /**
     * @var string Models namespace.
     * Can be required for data deserialization when model contains referenced schemas.
     */
    protected const MODELS_NAMESPACE = '\Mydex\ApiIdaasSdk\Slim4\Model';

    /**
     * @var string Constant with OAS schema of current class.
     * Should be overwritten by inherited class.
     */
    protected const MODEL_SCHEMA = <<<'SCHEMA'
{
  "type" : "object",
  "properties" : {
    "message" : {
      "type" : "string",
      "example" : "Access denied"
    },
    "reason" : {
      "type" : "string",
      "example" : "The token is invalid or expired"
    }
  }
}
SCHEMA;
}
