<?php

/**
 * IDaaS API
 * PHP version 8.1
 *
 * @package Mydex\ApiIdaasSdk\Slim4
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * Identity as a Service API for member authentication, identifiers, and account management.
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace Mydex\ApiIdaasSdk\Slim4\Model;

use Mydex\ApiIdaasSdk\Slim4\BaseModel;

/**
 * FtcSetupRequestBody
 *
 * @package Mydex\ApiIdaasSdk\Slim4\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class FtcSetupRequestBody extends BaseModel
{
    /**
     * @var string Models namespace.
     * Can be required for data deserialization when model contains referenced schemas.
     */
    protected const MODELS_NAMESPACE = '\Mydex\ApiIdaasSdk\Slim4\Model';

    /**
     * @var string Constant with OAS schema of current class.
     * Should be overwritten by inherited class.
     */
    protected const MODEL_SCHEMA = <<<'SCHEMA'
{
  "required" : [ "connection_nid", "connection_token_hash", "return_to" ],
  "type" : "object",
  "properties" : {
    "connection_nid" : {
      "type" : "string",
      "description" : "The connection NID",
      "example" : "123"
    },
    "connection_token_hash" : {
      "type" : "string",
      "description" : "The hashed connection token",
      "example" : "abc123hashed"
    },
    "return_to" : {
      "type" : "string",
      "description" : "The URL to return to after connection",
      "example" : "https://example.com/callback"
    },
    "mydexid" : {
      "type" : "string",
      "description" : "The MydexID if already known (required if version > 1)",
      "nullable" : true,
      "example" : "mydex123"
    },
    "version" : {
      "type" : "integer",
      "description" : "The connection version (default 1, must be >= 1)",
      "example" : 1
    },
    "linking_token" : {
      "type" : "string",
      "description" : "A unique ID representing the member in the subscriber's backend",
      "nullable" : true,
      "example" : "unique_linking_token"
    }
  },
  "description" : "Request body for First Time Connection setup"
}
SCHEMA;
}
