<?php

/**
 * IDaaS API
 * PHP version 8.1
 *
 * @package Mydex\ApiIdaasSdk\Slim4
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * Identity as a Service API for member authentication, identifiers, and account management.
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace Mydex\ApiIdaasSdk\Slim4\Model;

use Mydex\ApiIdaasSdk\Slim4\BaseModel;

/**
 * IdentifierObject
 *
 * @package Mydex\ApiIdaasSdk\Slim4\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class IdentifierObject extends BaseModel
{
    /**
     * @var string Models namespace.
     * Can be required for data deserialization when model contains referenced schemas.
     */
    protected const MODELS_NAMESPACE = '\Mydex\ApiIdaasSdk\Slim4\Model';

    /**
     * @var string Constant with OAS schema of current class.
     * Should be overwritten by inherited class.
     */
    protected const MODEL_SCHEMA = <<<'SCHEMA'
{
  "type" : "object",
  "properties" : {
    "id" : {
      "type" : "string",
      "description" : "Database ID of the identifier",
      "example" : "123"
    },
    "identifier" : {
      "type" : "string",
      "description" : "The UUID identifier",
      "format" : "uuid",
      "example" : "550e8400-e29b-41d4-a716-446655440000"
    },
    "parent_uuid" : {
      "type" : "string",
      "description" : "The parent identifier UUID if this is a child",
      "format" : "uuid",
      "nullable" : true,
      "example" : "660e8400-e29b-41d4-a716-446655440000"
    },
    "type" : {
      "type" : "string",
      "description" : "The type of identifier",
      "example" : "identifier"
    },
    "created" : {
      "type" : "string",
      "description" : "Creation timestamp",
      "example" : "2024-01-15 10:30:00"
    }
  },
  "description" : "An identifier record"
}
SCHEMA;
}
