<?php

/**
 * IDaaS API
 * PHP version 8.1
 *
 * @package Mydex\ApiIdaasSdk\Slim4
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * Identity as a Service API for member authentication, identifiers, and account management.
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace Mydex\ApiIdaasSdk\Slim4\Model;

use Mydex\ApiIdaasSdk\Slim4\BaseModel;

/**
 * InviteRequestBody
 *
 * @package Mydex\ApiIdaasSdk\Slim4\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class InviteRequestBody extends BaseModel
{
    /**
     * @var string Models namespace.
     * Can be required for data deserialization when model contains referenced schemas.
     */
    protected const MODELS_NAMESPACE = '\Mydex\ApiIdaasSdk\Slim4\Model';

    /**
     * @var string Constant with OAS schema of current class.
     * Should be overwritten by inherited class.
     */
    protected const MODEL_SCHEMA = <<<'SCHEMA'
{
  "required" : [ "app_url", "client_id", "con_nid", "identifier", "item_id", "message_email", "org_id", "project_id", "type" ],
  "type" : "object",
  "properties" : {
    "identifier" : {
      "type" : "string",
      "description" : "The parent identifier",
      "format" : "uuid",
      "example" : "550e8400-e29b-41d4-a716-446655440000"
    },
    "app_url" : {
      "type" : "string",
      "description" : "The application URL",
      "example" : "https://example.com"
    },
    "client_id" : {
      "type" : "string",
      "description" : "The OAuth2 client ID",
      "example" : "client123"
    },
    "con_nid" : {
      "type" : "string",
      "description" : "The connection NID",
      "example" : "456"
    },
    "org_id" : {
      "type" : "string",
      "description" : "The organization ID",
      "example" : "org789"
    },
    "project_id" : {
      "type" : "string",
      "description" : "The project ID",
      "example" : "proj123"
    },
    "item_id" : {
      "type" : "string",
      "description" : "The item ID",
      "example" : "item456"
    },
    "type" : {
      "type" : "string",
      "description" : "The type of invitation",
      "example" : "identifier"
    },
    "message_email" : {
      "type" : "string",
      "description" : "Email message content",
      "example" : "Please complete your registration"
    },
    "message_sms" : {
      "type" : "string",
      "description" : "SMS message content",
      "nullable" : true,
      "example" : "Please complete your registration"
    }
  },
  "description" : "Request body for storing and sending an identifier invite"
}
SCHEMA;
}
