<?php

/**
 * IDaaS API
 * PHP version 8.1
 *
 * @package Mydex\ApiIdaasSdk\Slim4
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * Identity as a Service API for member authentication, identifiers, and account management.
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace Mydex\ApiIdaasSdk\Slim4\Model;

use Mydex\ApiIdaasSdk\Slim4\BaseModel;

/**
 * NotifyMemberRequestBody
 *
 * @package Mydex\ApiIdaasSdk\Slim4\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class NotifyMemberRequestBody extends BaseModel
{
    /**
     * @var string Models namespace.
     * Can be required for data deserialization when model contains referenced schemas.
     */
    protected const MODELS_NAMESPACE = '\Mydex\ApiIdaasSdk\Slim4\Model';

    /**
     * @var string Constant with OAS schema of current class.
     * Should be overwritten by inherited class.
     */
    protected const MODEL_SCHEMA = <<<'SCHEMA'
{
  "required" : [ "identifier_auth", "message_email" ],
  "type" : "object",
  "properties" : {
    "identifier_auth" : {
      "$ref" : "#/components/schemas/IdentifierAuthObject"
    },
    "message_email" : {
      "type" : "string",
      "description" : "Email message content",
      "example" : "Please verify your identity"
    },
    "message_sms" : {
      "type" : "string",
      "description" : "SMS message content",
      "nullable" : true,
      "example" : "Please verify your identity"
    }
  },
  "description" : "Request body for sending a notification to a member"
}
SCHEMA;
}
