<?php

/**
 * IDaaS API
 * PHP version 8.1
 *
 * @package Mydex\ApiIdaasSdk\Slim4
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * Identity as a Service API for member authentication, identifiers, and account management.
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


declare(strict_types=1);

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */
namespace Mydex\ApiIdaasSdk\Slim4\App;

use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Slim\Exception\HttpNotImplementedException;
use Dyorg\TokenAuthentication;
use Mydex\ApiIdaasSdk\Slim4\Auth\OAuthAuthenticator;

/**
 * RegisterRoutes Class Doc Comment
 *
 * @package Mydex\ApiIdaasSdk\Slim4
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class RegisterRoutes
{
    /** @var array[] list of all api operations */
    private $operations = [
        [
            'httpMethod' => 'POST',
            'basePathWithoutHost' => '',
            'path' => '/ftc/setup',
            'apiPackage' => 'Mydex\ApiIdaasSdk\Slim4\Api',
            'classname' => 'AbstractConnectionsApi',
            'userClassname' => 'ConnectionsApi',
            'operationId' => 'postFtcSetup',
            'responses' => [
                '201' => [
                    'jsonSchema' => '{
  "description" : "Successfully created FTC setup URL.",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/FtcUrlResponse"
      }
    }
  }
}',
                ],
                '400' => [
                    'jsonSchema' => '{
  "description" : "Bad Request",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/ErrorResponse"
      }
    }
  }
}',
                ],
                '401' => [
                    'jsonSchema' => '{
  "description" : "Unauthorized",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/AuthErrorResponse"
      }
    }
  }
}',
                ],
            ],
            'authMethods' => [
                // oauth2 security schema named 'oauth2'
                [
                    'type' => 'oauth2',
                    'isBasic' => false,
                    'isBearer' => false,
                    'isApiKey' => false,
                    'isOAuth' => true,
                    'scopes' => [
                        'mydex:pdx', // Global access scope for connections endpoints
                    ],
                ],
            ],
        ],
        [
            'httpMethod' => 'POST',
            'basePathWithoutHost' => '',
            'path' => '/identify',
            'apiPackage' => 'Mydex\ApiIdaasSdk\Slim4\Api',
            'classname' => 'AbstractConnectionsApi',
            'userClassname' => 'ConnectionsApi',
            'operationId' => 'postIdentify',
            'responses' => [
                '201' => [
                    'jsonSchema' => '{
  "description" : "Successfully created identify URL.",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/IdentifyUrlResponse"
      }
    }
  }
}',
                ],
                '400' => [
                    'jsonSchema' => '{
  "description" : "Bad Request",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/ErrorResponse"
      }
    }
  }
}',
                ],
                '401' => [
                    'jsonSchema' => '{
  "description" : "Unauthorized",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/AuthErrorResponse"
      }
    }
  }
}',
                ],
            ],
            'authMethods' => [
                // oauth2 security schema named 'oauth2'
                [
                    'type' => 'oauth2',
                    'isBasic' => false,
                    'isBearer' => false,
                    'isApiKey' => false,
                    'isOAuth' => true,
                    'scopes' => [
                        'mydex:pdx', // Global access scope for connections endpoints
                    ],
                ],
            ],
        ],
        [
            'httpMethod' => 'PATCH',
            'basePathWithoutHost' => '',
            'path' => '/members/notify/status',
            'apiPackage' => 'Mydex\ApiIdaasSdk\Slim4\Api',
            'classname' => 'AbstractIdentifiersApi',
            'userClassname' => 'IdentifiersApi',
            'operationId' => 'patchNotifyStatus',
            'responses' => [
                '200' => [
                    'jsonSchema' => '{
  "description" : "Successfully updated notification status.",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/CreateIdentifierResponse"
      }
    }
  }
}',
                ],
                '400' => [
                    'jsonSchema' => '{
  "description" : "Bad Request",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/ErrorResponse"
      }
    }
  }
}',
                ],
                '401' => [
                    'jsonSchema' => '{
  "description" : "Unauthorized",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/AuthErrorResponse"
      }
    }
  }
}',
                ],
            ],
            'authMethods' => [
                // oauth2 security schema named 'oauth2'
                [
                    'type' => 'oauth2',
                    'isBasic' => false,
                    'isBearer' => false,
                    'isApiKey' => false,
                    'isOAuth' => true,
                    'scopes' => [
                        'mydex:identifiers', // Access to identifiers endpoints
                    ],
                ],
            ],
        ],
        [
            'httpMethod' => 'POST',
            'basePathWithoutHost' => '',
            'path' => '/members/invite/status',
            'apiPackage' => 'Mydex\ApiIdaasSdk\Slim4\Api',
            'classname' => 'AbstractIdentifiersApi',
            'userClassname' => 'IdentifiersApi',
            'operationId' => 'postInviteStatus',
            'responses' => [
                '200' => [
                    'jsonSchema' => '{
  "description" : "Successfully checked invite status.",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/InviteStatusResponse"
      }
    }
  }
}',
                ],
                '401' => [
                    'jsonSchema' => '{
  "description" : "Unauthorized",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/AuthErrorResponse"
      }
    }
  }
}',
                ],
            ],
            'authMethods' => [
                // oauth2 security schema named 'oauth2'
                [
                    'type' => 'oauth2',
                    'isBasic' => false,
                    'isBearer' => false,
                    'isApiKey' => false,
                    'isOAuth' => true,
                    'scopes' => [
                        'mydex:identifiers', // Access to identifiers endpoints
                    ],
                ],
            ],
        ],
        [
            'httpMethod' => 'POST',
            'basePathWithoutHost' => '',
            'path' => '/members/notify',
            'apiPackage' => 'Mydex\ApiIdaasSdk\Slim4\Api',
            'classname' => 'AbstractIdentifiersApi',
            'userClassname' => 'IdentifiersApi',
            'operationId' => 'postNotifyMemberViaIdentifier',
            'responses' => [
                '200' => [
                    'jsonSchema' => '{
  "description" : "Successfully sent notification.",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/CreateIdentifierResponse"
      }
    }
  }
}',
                ],
                '400' => [
                    'jsonSchema' => '{
  "description" : "Bad Request",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/ErrorResponse"
      }
    }
  }
}',
                ],
                '401' => [
                    'jsonSchema' => '{
  "description" : "Unauthorized",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/AuthErrorResponse"
      }
    }
  }
}',
                ],
            ],
            'authMethods' => [
                // oauth2 security schema named 'oauth2'
                [
                    'type' => 'oauth2',
                    'isBasic' => false,
                    'isBearer' => false,
                    'isApiKey' => false,
                    'isOAuth' => true,
                    'scopes' => [
                        'mydex:identifiers', // Access to identifiers endpoints
                    ],
                ],
            ],
        ],
        [
            'httpMethod' => 'POST',
            'basePathWithoutHost' => '',
            'path' => '/members/invite',
            'apiPackage' => 'Mydex\ApiIdaasSdk\Slim4\Api',
            'classname' => 'AbstractIdentifiersApi',
            'userClassname' => 'IdentifiersApi',
            'operationId' => 'postStoreAndSendIdentifierInvite',
            'responses' => [
                '200' => [
                    'jsonSchema' => '{
  "description" : "Successfully stored invitation and sent notification.",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/GetInviteResponse"
      }
    }
  }
}',
                ],
                '400' => [
                    'jsonSchema' => '{
  "description" : "Bad Request",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/ErrorResponse"
      }
    }
  }
}',
                ],
                '401' => [
                    'jsonSchema' => '{
  "description" : "Unauthorized",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/AuthErrorResponse"
      }
    }
  }
}',
                ],
            ],
            'authMethods' => [
                // oauth2 security schema named 'oauth2'
                [
                    'type' => 'oauth2',
                    'isBasic' => false,
                    'isBearer' => false,
                    'isApiKey' => false,
                    'isOAuth' => true,
                    'scopes' => [
                        'mydex:identifiers', // Access to identifiers endpoints
                    ],
                ],
            ],
        ],
        [
            'httpMethod' => 'GET',
            'basePathWithoutHost' => '',
            'path' => '/members/invite/{invite}',
            'apiPackage' => 'Mydex\ApiIdaasSdk\Slim4\Api',
            'classname' => 'AbstractIdentifiersApi',
            'userClassname' => 'IdentifiersApi',
            'operationId' => 'getIdentifierInvite',
            'responses' => [
                '200' => [
                    'jsonSchema' => '{
  "description" : "Successfully retrieved invitation.",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/GetInviteResponse"
      }
    }
  }
}',
                ],
                '401' => [
                    'jsonSchema' => '{
  "description" : "Unauthorized",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/AuthErrorResponse"
      }
    }
  }
}',
                ],
            ],
            'authMethods' => [
                // oauth2 security schema named 'oauth2'
                [
                    'type' => 'oauth2',
                    'isBasic' => false,
                    'isBearer' => false,
                    'isApiKey' => false,
                    'isOAuth' => true,
                    'scopes' => [
                        'mydex:identifiers', // Access to identifiers endpoints
                    ],
                ],
            ],
        ],
        [
            'httpMethod' => 'GET',
            'basePathWithoutHost' => '',
            'path' => '/members/myaccount/{svt}',
            'apiPackage' => 'Mydex\ApiIdaasSdk\Slim4\Api',
            'classname' => 'AbstractMyAccountApi',
            'userClassname' => 'MyAccountApi',
            'operationId' => 'getMydexIdFromMyAccountSvt',
            'responses' => [
                '200' => [
                    'jsonSchema' => '{
  "description" : "Successfully retrieved MydexID.",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/MyAccountLookupResponse"
      }
    }
  }
}',
                ],
                '400' => [
                    'jsonSchema' => '{
  "description" : "Bad Request",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/ErrorResponse"
      }
    }
  }
}',
                ],
                '401' => [
                    'jsonSchema' => '{
  "description" : "Unauthorized",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/AuthErrorResponse"
      }
    }
  }
}',
                ],
            ],
            'authMethods' => [
                // oauth2 security schema named 'oauth2'
                [
                    'type' => 'oauth2',
                    'isBasic' => false,
                    'isBearer' => false,
                    'isApiKey' => false,
                    'isOAuth' => true,
                    'scopes' => [
                        'mydex:myaccount', // Access to MyAccount-to-MydexID mapping
                    ],
                ],
            ],
        ],
        [
            'httpMethod' => 'GET',
            'basePathWithoutHost' => '',
            'path' => '/members/scotaccount/{sub}',
            'apiPackage' => 'Mydex\ApiIdaasSdk\Slim4\Api',
            'classname' => 'AbstractScotAccountApi',
            'userClassname' => 'ScotAccountApi',
            'operationId' => 'getMydexIdFromScotAccountSub',
            'responses' => [
                '200' => [
                    'jsonSchema' => '{
  "description" : "Successfully retrieved MydexID.",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/ScotAccountLookupResponse"
      }
    }
  }
}',
                ],
                '400' => [
                    'jsonSchema' => '{
  "description" : "Bad Request",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/ErrorResponse"
      }
    }
  }
}',
                ],
                '401' => [
                    'jsonSchema' => '{
  "description" : "Unauthorized",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/AuthErrorResponse"
      }
    }
  }
}',
                ],
            ],
            'authMethods' => [
                // oauth2 security schema named 'oauth2'
                [
                    'type' => 'oauth2',
                    'isBasic' => false,
                    'isBearer' => false,
                    'isApiKey' => false,
                    'isOAuth' => true,
                    'scopes' => [
                        'mydex:scotaccount', // Access to ScotAccount-to-MydexID mapping
                    ],
                ],
            ],
        ],
    ];

    /**
     * Add routes to Slim app.
     *
     * @param \Slim\App $app Pre-configured Slim application instance
     *
     * @throws HttpNotImplementedException When implementation class doesn't exists
     */
    public function __invoke(\Slim\App $app): void
    {
        $app->options('/{routes:.*}', function (ServerRequestInterface $request, ResponseInterface $response) {
            // CORS Pre-Flight OPTIONS Request Handler
            return $response;
        });

        // create mock middleware factory
        /** @var \Psr\Container\ContainerInterface */
        $container = $app->getContainer();
        /** @var \OpenAPIServer\Mock\OpenApiDataMockerRouteMiddlewareFactory|null */
        $mockMiddlewareFactory = null;
        if ($container->has(\OpenAPIServer\Mock\OpenApiDataMockerRouteMiddlewareFactory::class)) {
            // I know, anti-pattern. Don't retrieve dependency directly from container
            $mockMiddlewareFactory = $container->get(\OpenAPIServer\Mock\OpenApiDataMockerRouteMiddlewareFactory::class);
        }

        foreach ($this->operations as $operation) {
            $callback = function (ServerRequestInterface $request) use ($operation) {
                $message = "How about extending {$operation['classname']} by {$operation['apiPackage']}\\{$operation['userClassname']} class implementing {$operation['operationId']} as a {$operation['httpMethod']} method?";
                throw new HttpNotImplementedException($request, $message);
            };
            $middlewares = [];

            if (class_exists("\\{$operation['apiPackage']}\\{$operation['userClassname']}")) {
                // Notice how we register the controller using the class name?
                // PHP-DI will instantiate the class for us only when it's actually necessary
                $callback = ["\\{$operation['apiPackage']}\\{$operation['userClassname']}", $operation['operationId']];
            }

            if ($mockMiddlewareFactory) {
                $mockSchemaResponses = array_map(function ($item) {
                    return json_decode($item['jsonSchema'], true);
                }, $operation['responses']);
                $middlewares[] = $mockMiddlewareFactory->create($mockSchemaResponses);
            }

            $route = $app->map(
                [$operation['httpMethod']],
                "{$operation['basePathWithoutHost']}{$operation['path']}",
                $callback
            )->setName($operation['operationId']);

            // Add authentication middleware based on the operation's authMethods
            if ($operation['authMethods']) {
                foreach ($operation['authMethods'] as $authMethod) {
                    if ($authMethod['isOAuth']) {
                        $route->add(new TokenAuthentication([
                            'path' => '/',
                            'authenticator' => new OAuthAuthenticator($authMethod['scopes']),
                            'regex' => '/Bearer\s+(.*)$/i',
                            'header' => 'Authorization',
                            'parameter' => null,
                            'cookie' => null,
                            'argument' => null,
                            'attribute' => 'authorization_token',
                            'error' => ['Mydex\ApiIdaasSdk\Slim4\Auth\OAuthAuthenticator', 'handleUnauthorized'],
                        ]));
                    }
                }
            }

            foreach ($middlewares as $middleware) {
                $route->add($middleware);
            }
        }
    }
}
