<?php

/**
 * IDaaS API
 * PHP version 8.1
 *
 * @package Mydex\ApiIdaasSdk\Slim4
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * Identity as a Service API for member authentication, identifiers, and account management.
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */
namespace Mydex\ApiIdaasSdk\Slim4\Model;

use PHPUnit\Framework\TestCase;
use Mydex\ApiIdaasSdk\Slim4\Model\IdentifyUrlResponse;

/**
 * IdentifyUrlResponseTest Class Doc Comment
 *
 * @package Mydex\ApiIdaasSdk\Slim4\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \Mydex\ApiIdaasSdk\Slim4\Model\IdentifyUrlResponse
 */
class IdentifyUrlResponseTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "IdentifyUrlResponse"
     */
    public function testIdentifyUrlResponse()
    {
        $testIdentifyUrlResponse = new IdentifyUrlResponse();
        $namespacedClassname = IdentifyUrlResponse::getModelsNamespace() . '\\IdentifyUrlResponse';
        $this->assertSame('\\' . IdentifyUrlResponse::class, $namespacedClassname);
        $this->assertTrue(
            class_exists($namespacedClassname),
            sprintf('Assertion failed that "%s" class exists', $namespacedClassname)
        );
        self::markTestIncomplete(
            'Test of "IdentifyUrlResponse" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
        self::markTestIncomplete(
            'Test of "url" property in "IdentifyUrlResponse" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "qr"
     */
    public function testPropertyQr()
    {
        self::markTestIncomplete(
            'Test of "qr" property in "IdentifyUrlResponse" model has not been implemented yet.'
        );
    }

    /**
     * Test getOpenApiSchema static method
     * @covers ::getOpenApiSchema
     */
    public function testGetOpenApiSchema()
    {
        $schemaArr = IdentifyUrlResponse::getOpenApiSchema();
        $this->assertIsArray($schemaArr);
    }
}

