<?php

/**
 * IDaaS API
 * PHP version 8.1
 *
 * @package Mydex\ApiIdaasSdk\Slim4
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * Identity as a Service API for member authentication, identifiers, and account management.
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */
namespace Mydex\ApiIdaasSdk\Slim4\Model;

use PHPUnit\Framework\TestCase;
use Mydex\ApiIdaasSdk\Slim4\Model\IdentifierAuthObject;

/**
 * IdentifierAuthObjectTest Class Doc Comment
 *
 * @package Mydex\ApiIdaasSdk\Slim4\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \Mydex\ApiIdaasSdk\Slim4\Model\IdentifierAuthObject
 */
class IdentifierAuthObjectTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "IdentifierAuthObject"
     */
    public function testIdentifierAuthObject()
    {
        $testIdentifierAuthObject = new IdentifierAuthObject();
        $namespacedClassname = IdentifierAuthObject::getModelsNamespace() . '\\IdentifierAuthObject';
        $this->assertSame('\\' . IdentifierAuthObject::class, $namespacedClassname);
        $this->assertTrue(
            class_exists($namespacedClassname),
            sprintf('Assertion failed that "%s" class exists', $namespacedClassname)
        );
        self::markTestIncomplete(
            'Test of "IdentifierAuthObject" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "parentUuid"
     */
    public function testPropertyParentUuid()
    {
        self::markTestIncomplete(
            'Test of "parentUuid" property in "IdentifierAuthObject" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "appUrl"
     */
    public function testPropertyAppUrl()
    {
        self::markTestIncomplete(
            'Test of "appUrl" property in "IdentifierAuthObject" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "clientId"
     */
    public function testPropertyClientId()
    {
        self::markTestIncomplete(
            'Test of "clientId" property in "IdentifierAuthObject" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "conNid"
     */
    public function testPropertyConNid()
    {
        self::markTestIncomplete(
            'Test of "conNid" property in "IdentifierAuthObject" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "orgId"
     */
    public function testPropertyOrgId()
    {
        self::markTestIncomplete(
            'Test of "orgId" property in "IdentifierAuthObject" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "projectId"
     */
    public function testPropertyProjectId()
    {
        self::markTestIncomplete(
            'Test of "projectId" property in "IdentifierAuthObject" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "itemId"
     */
    public function testPropertyItemId()
    {
        self::markTestIncomplete(
            'Test of "itemId" property in "IdentifierAuthObject" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
        self::markTestIncomplete(
            'Test of "type" property in "IdentifierAuthObject" model has not been implemented yet.'
        );
    }

    /**
     * Test getOpenApiSchema static method
     * @covers ::getOpenApiSchema
     */
    public function testGetOpenApiSchema()
    {
        $schemaArr = IdentifierAuthObject::getOpenApiSchema();
        $this->assertIsArray($schemaArr);
    }
}

