<?php

/**
 * IDaaS API
 * PHP version 8.1
 *
 * @package Mydex\ApiIdaasSdk\Slim4
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * Identity as a Service API for member authentication, identifiers, and account management.
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */
namespace Mydex\ApiIdaasSdk\Slim4\Model;

use PHPUnit\Framework\TestCase;
use Mydex\ApiIdaasSdk\Slim4\Model\InviteStatusResponse;

/**
 * InviteStatusResponseTest Class Doc Comment
 *
 * @package Mydex\ApiIdaasSdk\Slim4\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \Mydex\ApiIdaasSdk\Slim4\Model\InviteStatusResponse
 */
class InviteStatusResponseTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "InviteStatusResponse"
     */
    public function testInviteStatusResponse()
    {
        $testInviteStatusResponse = new InviteStatusResponse();
        $namespacedClassname = InviteStatusResponse::getModelsNamespace() . '\\InviteStatusResponse';
        $this->assertSame('\\' . InviteStatusResponse::class, $namespacedClassname);
        $this->assertTrue(
            class_exists($namespacedClassname),
            sprintf('Assertion failed that "%s" class exists', $namespacedClassname)
        );
        self::markTestIncomplete(
            'Test of "InviteStatusResponse" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "success"
     */
    public function testPropertySuccess()
    {
        self::markTestIncomplete(
            'Test of "success" property in "InviteStatusResponse" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
        self::markTestIncomplete(
            'Test of "status" property in "InviteStatusResponse" model has not been implemented yet.'
        );
    }

    /**
     * Test getOpenApiSchema static method
     * @covers ::getOpenApiSchema
     */
    public function testGetOpenApiSchema()
    {
        $schemaArr = InviteStatusResponse::getOpenApiSchema();
        $this->assertIsArray($schemaArr);
    }
}

