<?php

/**
 * IDaaS API
 * PHP version 8.1
 *
 * @package Mydex\ApiIdaasSdk\Slim4
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * Identity as a Service API for member authentication, identifiers, and account management.
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */
namespace Mydex\ApiIdaasSdk\Slim4\Model;

use PHPUnit\Framework\TestCase;
use Mydex\ApiIdaasSdk\Slim4\Model\NotifyMemberRequestBody;

/**
 * NotifyMemberRequestBodyTest Class Doc Comment
 *
 * @package Mydex\ApiIdaasSdk\Slim4\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \Mydex\ApiIdaasSdk\Slim4\Model\NotifyMemberRequestBody
 */
class NotifyMemberRequestBodyTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "NotifyMemberRequestBody"
     */
    public function testNotifyMemberRequestBody()
    {
        $testNotifyMemberRequestBody = new NotifyMemberRequestBody();
        $namespacedClassname = NotifyMemberRequestBody::getModelsNamespace() . '\\NotifyMemberRequestBody';
        $this->assertSame('\\' . NotifyMemberRequestBody::class, $namespacedClassname);
        $this->assertTrue(
            class_exists($namespacedClassname),
            sprintf('Assertion failed that "%s" class exists', $namespacedClassname)
        );
        self::markTestIncomplete(
            'Test of "NotifyMemberRequestBody" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "identifierAuth"
     */
    public function testPropertyIdentifierAuth()
    {
        self::markTestIncomplete(
            'Test of "identifierAuth" property in "NotifyMemberRequestBody" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "messageEmail"
     */
    public function testPropertyMessageEmail()
    {
        self::markTestIncomplete(
            'Test of "messageEmail" property in "NotifyMemberRequestBody" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "messageSms"
     */
    public function testPropertyMessageSms()
    {
        self::markTestIncomplete(
            'Test of "messageSms" property in "NotifyMemberRequestBody" model has not been implemented yet.'
        );
    }

    /**
     * Test getOpenApiSchema static method
     * @covers ::getOpenApiSchema
     */
    public function testGetOpenApiSchema()
    {
        $schemaArr = NotifyMemberRequestBody::getOpenApiSchema();
        $this->assertIsArray($schemaArr);
    }
}

